### ISSUE TITLE
Exclude symlinks

### ISSUE THREAD

**Issue by liyishuai** [olivernybroe/action-conflict-finder#6]
Say `foo` symlinks to a directory that does not exist before compilation, and my compilation CI is not on GitHub Actions, then checkout followed by conflict finder fails with:
> grep: ./foo: No such file or directory

Is it worth excluding symlinks by default?

**Comment by olivernybroe** [comment]
Hmm, let's think about this.

So if a symlink exists and we are able to resolve it inside of the repository, then the path the symlink is pointing to will already be scanned, if we cannot resolve the symlink, then we cannot scan the file either way. 

So by that logic I think it should be safe to exclude symlinks 🤔

**Comment by olivernybroe** [comment]
According to `grep` docs, I think this solve be as simple as just changing the `-R` to a ´-r` instead.
http://www.gnu.org/software/grep/manual/grep.html#index-_002dr

**Comment by olivernybroe** [comment]
@liyishuai sorry totally forgot about making a pr for this, luckily it has been done now and a release is out 👍
