### ISSUE TITLE
Who uses Merge Conflict?

### ISSUE THREAD

**Issue by italosantana** [olivernybroe/action-conflict-finder#8]
Better to create a separate workflow to perform this verification or create a test-only one and add it? Any suggestion?

**Comment by olivernybroe** [comment]
@italosantana could you please elaborate on what you mean? 

From what I gather is you are interested in knowing how others have setup this action? For me I have a separate workflow called `code-analysis.yml`, this contains all my static analysis tools, where this merge conflict finder action is one of the jobs it runs.
